# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: bacterial_wgs_training
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  ## conda-forge packages
  - conda-forge::python=3.6.10
  - conda-forge::r-base=3.6.2
  - conda-forge::r-optparse=1.6.6
  - conda-forge::r-tidyr=1.1.0
  - conda-forge::r-tidyverse=1.3.0
  - conda-forge::r-ggplot2=3.3.1
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-viridis=0.5.1

  ## bioconda packages
  ## common
  - bioconda::fastqc=0.11.9
  - bioconda::fastp=0.20.1
  - bioconda::samtools=1.9
  - bioconda::bedtools=2.29.2
  - bioconda::multiqc=1.9
  - bioconda::bwa=0.7.17
  - bioconda::picard=2.23.0
  - bioconda::bcftools=1.9
  - bioconda::kraken2=2.0.9beta
  - bioconda::unicycler=0.4.7
  - bioconda::quast=5.0.2
  - bioconda::plasmidid=1.6.5
  - bioconda::prokka=1.14.5
  - bioconda::abacas=1.3.1
  - bioconda::chewbbaca=2.8.4
  - bioconda::gubbins=2.3.4
  - bioconda::snippy
  - bioconda::iqtree
