name: tests ci
# This workflow runs the pipeline with the minimal test dataset to check that it completes any errors
on:
  push:
    branches: [one_week_format]
  pull_request_target:
    branches: [one_week_format]
  release:
    types: [published]

jobs:
  push_dockerhub:
    name: Push new Docker image to Docker Hub (dev)
    runs-on: ubuntu-latest
    # Only run for the official repo, for releases and merged PRs
    if: ${{ github.repository == 'BU-ISCIII/bacterial_wgs_training' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v2

      - name: Build new docker image
        run: docker build --no-cache . -t buisciii/bacterial_wgs_training:dev

      - name: Push Docker image to DockerHub (develop)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push buisciii/bacterial_wgs_training:dev
